# -*- coding: utf-8 -*-
"""CIE 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qFv9OwHiObWacC_G7J1CTtTFRFTLnPdO
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df = pd.read_csv('Mall_Customers.csv')
df

from sklearn.cluster import KMeans
wcss_list= []

for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(x)
    wcss_list.append(kmeans.inertia_)

plt.plot(range(1, 11), wcss_list)
plt.title('The Elbow Method Graph')
plt.xlabel('Number of clusters (k)')
plt.ylabel('WCSS (Within-Cluster Sum of Squares)')
plt.show()

kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)
y_predict = kmeans.fit_predict(x)

#visulaize the clusters
cluster1=plt.scatter(x[y_predict == 0, 0], x[y_predict == 0, 1], s = 100, c = 'green',label = 'Cluster 1') #for first cluster
cluster2=plt.scatter(x[y_predict == 1, 0], x[y_predict == 1, 1], s = 100, c = 'blue',label = ' Cluster 2') #for second cluster
cluster=plt.scatter(x[y_predict== 2, 0], x[y_predict == 2, 1], s = 100, c = 'black',label = 'Cluster 3') #for third cluster
cluster3=plt.scatter(x[y_predict == 3, 0], x[y_predict == 3, 1], s = 100, c = 'cyan',label = 'Cluster 4') #for fourth cluster
cluster5=plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s= 300, c = 'yellow', label = 'Centroid')
plt.title('visualize the clusters')
plt.xlabel('Annual Income (k$)')
plt.ylabel('')
plt.legend()
plt.show()

x = df.iloc[:, [3, 4]].values
x