# -*- coding: utf-8 -*-
"""CIE-3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14nmVeKTrupGG9gae0r5VG4RkaJ65MM25
"""

import pandas as pd

df = pd.read_csv('Housing1.csv')
df.head()
df1=df[['area','bedrooms','bathrooms','stories','price']]
df1.head()

"""# data exploration"""

df.head()

df.tail()

df.describe()

df.isnull().sum()

df.sum()

df.info()

"""# Split data"""

x=df1.drop('price',axis=1)
y=df1['price']
print("shape of x=",x.shape)
print("shape of y=",y.shape)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=54)
print('Shape of X_train',x_train.shape)
print('Shape of X_test',x_test.shape)
print('Shape of y_train',y_train.shape)
print('Shape of y_test',y_test.shape)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 51)

print('Shape of X_train',X_train.shape)
print('Shape of X_test',X_test.shape)
print('Shape of Y_train',y_train.shape)
print('Shape of Y_test',y_test.shape)

x_train

import pandas as pd
df=pd.read_csv("Iris.csv")
df

df.head()

df.tail()

df.describe()

df.info()

df.isnull().sum()

df.sum()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=24)
print( 'X_train',x_train.shape)
print('Shape of X_test',x_test.shape)
print('Shape of y_train',y_train.shape)
print('Shape of y_test',y_test.shape)

